# Keith Galli 

https://youtu.be/GB9ByFAIAH4

In [1]:
import numpy as np

## Basics

In [28]:
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [18]:
a.ndim

1

In [29]:
a.dtype

dtype('int16')

In [25]:
a.shape

(3,)

In [22]:
# Bytes
a.itemsize

2

In [30]:
b = np.array([[9.0, 3.0, 2.0], [4.0, 5.0, 6.0], [7.0, 3.0, 5.0]])
print(b)

[[9. 3. 2.]
 [4. 5. 6.]
 [7. 3. 5.]]


In [16]:
b.shape

(3, 3)

In [31]:
b.dtype

dtype('float64')

In [58]:
b.ndim

2

In [23]:
# Bytes
b.itemsize

8

In [34]:
# Total elements
b.size

9

In [33]:
# Total size (itemsize*size)
b.nbytes

72

In [32]:
# Total elements
b.size

9

## Acessing/Changing specific elements, rows, columns, etc

In [90]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [39]:
# specific element
a[1,5]

13

In [40]:
# specific column
a[:,2]

array([ 3, 10])

In [44]:
# specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [47]:
# [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [56]:
a[1,5] = 100
print(a)

a[:, 2] = [44,55]
a

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 100  14]]


array([[  1,   2,  44,   4,   5,   6,   7],
       [  8,   9,  55,  11,  12, 100,  14]])

#### `PLAY WITH DIMENSIONS`

In [75]:
arr = np.array([[[1,4]],[[5,8]]]) # vs ([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 4]]

 [[5 8]]]


In [73]:
arr.ndim

3

In [76]:
arr.shape

(2, 1, 2)

#### `3-d EXAMPLE`

In [77]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [78]:
b.ndim

3

In [83]:
# specific element
# (**** WORK outside to inside ****)
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [84]:
# replace
b[:,1,:] = [[9,9],[8,8]]

In [85]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Types of Arrays 

In [5]:
np.array([3,5,6,3])

array([3, 5, 6, 3])

In [86]:
# All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [87]:
# All 1s matrix
np.ones((3,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [4]:
# Specify range but not size
np.arange(4)

array([0, 1, 2, 3])

In [88]:
# Any other number
np.full((2,2), 88)    # or np.full(a.shape, 00)

array([[88, 88],
       [88, 88]])

In [91]:
# Any other number (full_like)
np.full_like(a, 99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [92]:
# Random decimal numbers
np.random.rand(4,2)    # or np.random.random_sample(a.shape)

array([[0.9406006 , 0.78512803],
       [0.24559432, 0.84814922],
       [0.63617961, 0.90232965],
       [0.38456282, 0.74554254]])

In [95]:
# Random integer
np.random.randint(8, size=(3,3))

array([[5, 4, 3],
       [2, 5, 2],
       [4, 0, 0]])

In [2]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)# 0-th axis
print(r1)
r2 = np.repeat(arr, 3, axis=1)# 1-th axis
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


EXERCISE

In [12]:
out = np.ones((5,5), dtype=int)
print(out)

z = np.zeros((3,3), dtype=int)
z[1,1] = 9
print(z)

out[1:-1,1:-1] = z
print(out)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [15]:
a = np.array([1,2,3])
b = a.copy()   # not b = a
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [16]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [17]:
a + 2

array([3, 4, 5, 6])

In [18]:
a * 2

array([2, 4, 6, 8])

In [19]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [20]:
a ** 2

array([ 1,  4,  9, 16])

In [25]:
a

array([1, 2, 3, 4])

In [21]:
# Take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

More Math Functions ----- https://numpy.org/doc/stable/reference/routines.math.html

## Linear Algebra 

In [28]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)


np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [3]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

####  Reference Docs

https://numpy.org/doc/stable/reference/routines.linalg.html 

1. Determinent
2. Trace 
3. Inverse 
4. Eigenvalues

## Statistics

In [9]:
# 
stats = np.array([[3,2,1],[4,5,6]])
stats

array([[3, 2, 1],
       [4, 5, 6]])

In [12]:
# Max in each row of x-axis
np.min(stats)
np.min(stats, axis=1)

array([1, 4])

In [16]:
# Max in each column of y-axis
np.max(stats, axis=0)

array([4, 5, 6])

## Reorganizing Arrays 

In [21]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print('Before', before, sep='\n', end='\n\n')

after = before.reshape((2,2,2))
print('After', after, sep='\n')

Before
[[1 2 3 4]
 [5 6 7 8]]

After
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
# Horizontally stacking vectors

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

LOAD DATA FROM FILE

In [28]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

BOOLEAN MASKING & ADVANCED INDEXING

In [31]:
## Can index with a list in NUMPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [34]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [32]:
# Any out of 3 axis
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [33]:
# All 3 axis 
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

EXERCISE

In [38]:
a1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(a1[[0,1],[1,2]])    # Index 0,1 & 1,2

[2 6]


In [47]:
print(a1[[0,-1], 1:3])

[[2 3]
 [8 9]]


In [22]:
arr = np.array([[2+1j, 3, 4], [2, 3, 4]], dtype=complex)

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
a

2
(2, 3)
6
complex128


array([[2.+1.j, 3.+0.j, 4.+0.j],
       [2.+0.j, 3.+0.j, 4.+0.j]])